version: "3.9"
   
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - '6379'
    ports:
      - "6379:6379"
    networks:
      - djangonetwork
      
      
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    networks:
      - djangonetwork
    environment:
      - POSTGRES_NAME=chatplatform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=chatplatform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - db
      
    networks:
      - djangonetwork
      
    links:
      - db
      - redis
     
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - db
      
    networks:
      - djangonetwork
      
    tty: true
      

      
networks: 
  djangonetwork:
    driver: bridge