# Generated by Django 4.0.3 on 2022-03-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0002_alter_chatmessage_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='ChatMessage',
        ),
        migrations.AlterModelTable(
            name='thread',
            table='Thread',
        ),
        migrations.AlterModelTable(
            name='threadmember',
            table='ThreadMember',
        ),
    ]
