# Generated by Django 4.0.3 on 2022-03-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0003_alter_chatmessage_table_alter_thread_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='timestamp',
            new_name='created',
        ),
    ]
