# Generated by Django 4.0.3 on 2022-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0004_rename_timestamp_thread_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
